package com.springboot.MyTodoList.model;


import jakarta.persistence.*;

/*
    representation of the USER table that exists already
    in the autonomous database

    CREATE TABLE TODOUSER.USERS (
        ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, -- ID autoincremental
        NAME VARCHAR2(50),        -- Campo para nombres, longitud máxima de 50 caracteres
        LASTNAME VARCHAR2(50),    -- Campo para apellidos, longitud máxima de 50 caracteres
        PHONENUMBER NUMBER(10),        -- Campo numérico, con un máximo de 10 dígitos
        USERPASSWORD VARCHAR2(100),    -- Campo para contraseñas, longitud máxima de 100 caracteres
        PRIMARY KEY (ID) -- Define ID como clave primaria
   );
 */
@Entity
@Table(name = "USERS")
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    int userId;

    @Column(name = "USERNAME")
    String username;

    @Column(name = "EMAIL")
    String email;

    @Column(name = "PHONE_NUMBER")
    Integer phoneNumber;

    @Column(name = "IS_MANAGER")
    Boolean isManager;

    @Column(name = "PASSWORD") // En la base de datos no tenemos password todavía
    String password;

    @Column(name = "TEAM_ID")
    Integer teamId;

    public User(){}

    public User(int userId, String username, String email, Integer phoneNumber, Boolean isManager, String password, Integer teamId){
        this.userId = userId;
        this.username = username;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.isManager = isManager;
        this.password = password;
        this.teamId = teamId;
    }

    public int getUserId(){
        return userId;
    }

    public void setUserId(int userId){
        this.userId = userId;
    }

    public String getUsername(){
        return username;
    }

    public void setUsername(String username){
        this.username = username;
    }

    public String getEmail(){
        return email;
    }

    public void setEmail(String email){
        this.email = email;
    }

    public Integer getPhoneNumber(){
        return phoneNumber;
    }

    public void setPhoneNumber(Integer phoneNumber){
        this.phoneNumber = phoneNumber;
    }

    public Boolean getIsManager(){
        return isManager;
    }

    public void setIsManager(Boolean isManager){
        this.isManager = isManager;
    }

    
    public String getPassword(){
        return password;
    }

    public void setPassword(String password){
        this.password=password;
    }

    public Integer getTeamId() {
        return teamId;
    }

    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

}