package com.springboot.MyTodoList.model;

import jakarta.persistence.*;

/*
   representation of the USER table that exists already
   in the autonomous database

   CREATE TABLE TODOUSER.USERS (
       ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY, -- ID autoincremental
       NAME VARCHAR2(50),        -- Campo para nombres, longitud máxima de 50 caracteres
       LASTNAME VARCHAR2(50),    -- Campo para apellidos, longitud máxima de 50 caracteres
       PHONENUMBER NUMBER(10),        -- Campo numérico, con un máximo de 10 dígitos
       USERPASSWORD VARCHAR2(100),    -- Campo para contraseñas, longitud máxima de 100 caracteres
       PRIMARY KEY (ID) -- Define ID como clave primaria
  );
*/
@Entity
@Table(name = "USERS")
public class User {
    //everything is nullable by default TODO change later all to not nullable
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int userId;
    @Column(name = "USERNAME")
    private String username;
    @Column(name = "PHONE_NUMBER")
    private Integer phoneNumber;    
    @Column(name = "EMAIL")
    private String email;
    @Column(name = "PASSWORD") // En la base de datos no tenemos password todavía
    private String password;
    @Column(name = "IS_MANAGER") //nullable
    private Boolean isManager;

    //foreign key
    @ManyToOne
    @JoinColumn(name = "TEAM_ID") //nullable
    private Team team;

    public User() {
    }

    public User(int userId, String username, String email, Integer phoneNumber, Boolean isManager, String password,
            Team teamId) {
        this.userId = userId;
        this.username = username;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.isManager = isManager;
        this.password = password;
        this.team = teamId;
    }

    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Integer getPhoneNumber() {
        return phoneNumber;
    }

    public void setPhoneNumber(Integer phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public Boolean getIsManager() {
        return isManager;
    }

    public void setIsManager(Boolean isManager) {
        this.isManager = isManager;
    }

    public String getUserPassword(){
        return password;
    }

    public void setUserPassword(String password) {
        this.password = password;
    }

    public Team getTeamId() {
        return team;
    }

    public void setTeamId(Team teamId) {
        this.team = teamId;
    }
}
